last_change = 2026-08-16T09:32:18.913218Z
addr = 0xac38d0
size = 0x12b
name = "CSource2Server_GetMatchmakingGameData"
type = "void"

[header]
name = "CSource2Server_GetMatchmakingGameData"
addr = 0xac38d0
type = "void"

[header.args]
