last_change = 2026-08-15T07:57:57.042774Z
addr = 0xac38d0
size = 0x12b
name = "CSource2Server_GetMatchmakingGameData"
type = "const char *"

[header]
name = "CSource2Server_GetMatchmakingGameData"
addr = 0xac38d0
type = "const char *"

[header.args]
