last_change = 2026-08-15T07:58:07.428142Z
addr = 0xae1d30
size = 0x871
name = "CCSPlayerPawn_Event_KilledOther"
type = "short"

[header]
name = "CCSPlayerPawn_Event_KilledOther"
addr = 0xae1d30
type = "short"

[header.args]
