last_change = 2026-08-16T09:32:30.328486Z
addr = 0xae1d30
size = 0x871
name = "CCSPlayerPawn_Event_KilledOther"
type = "short"

[header]
name = "CCSPlayerPawn_Event_KilledOther"
addr = 0xae1d30
type = "short"

[header.args]
