last_change = 2026-08-16T09:32:30.549151Z
addr = 0xaf8520
size = 0x1ce5
name = "CCSPlayerPawn_Event_Killed"
type = "long long"

[header]
name = "CCSPlayerPawn_Event_Killed"
addr = 0xaf8520
type = "long long"

[header.args]
