last_change = 2026-08-15T07:57:57.042803Z
addr = 0xafa420
size = 0xcc6
name = "CNetworkUtlVectorEmbedded_NetworkStateChanged_m_perRoundStats"
type = "long long"

[header]
name = "CNetworkUtlVectorEmbedded_NetworkStateChanged_m_perRoundStats"
addr = 0xafa420
type = "long long"

[header.args]
