last_change = 2026-08-15T07:57:57.042808Z
addr = 0xb0ca70
size = 0xd3
name = "ClientPutInServer"
type = "long long"

[header]
name = "ClientPutInServer"
addr = 0xb0ca70
type = "long long"

[header.args]
