last_change = 2026-08-16T09:32:30.913145Z
addr = 0xb9a390
size = 0x18e
name = "CGameMoney_OnMoneySpent"
type = "unsigned long long *"

[header]
name = "CGameMoney_OnMoneySpent"
addr = 0xb9a390
type = "unsigned long long *"

[header.args]
