last_change = 2026-08-15T07:58:08.004359Z
addr = 0xb9a390
size = 0x18e
name = "CGameMoney_OnMoneySpent"
type = "long long"

[header]
name = "CGameMoney_OnMoneySpent"
addr = 0xb9a390
type = "long long"

[header.args]
