last_change = 2026-08-16T09:32:31.277604Z
addr = 0xbffdb0
size = 0x1aa9
name = "CCSBot_UpdatePathMovement"
type = "long long"

[header]
name = "CCSBot_UpdatePathMovement"
addr = 0xbffdb0
type = "long long"

[header.args]
