last_change = 2026-08-15T07:57:57.042869Z
addr = 0xc08b50
size = 0x1e8
name = "BotKill_CommandHandler"
type = "long long"

[header]
name = "BotKill_CommandHandler"
addr = 0xc08b50
type = "long long"

[header.args]
