last_change = 2026-08-15T07:57:57.042885Z
addr = 0xc39c50
size = 0x57c
name = "CBtActionCoordinatedBuy_Update"
type = "long long"

[header]
name = "CBtActionCoordinatedBuy_Update"
addr = 0xc39c50
type = "long long"

[header.args]
