last_change = 2026-08-16T09:32:32.152942Z
addr = 0xd4f990
size = 0x4bd
name = "CBaseEntity_SpawnRadius"
type = "long long"

[header]
name = "CBaseEntity_SpawnRadius"
addr = 0xd4f990
type = "long long"

[header.args]
