last_change = 2026-08-15T07:57:57.042936Z
addr = 0xd51100
size = 0xd15
name = "CBaseEntity_TakeDamageOld"
type = "long long"

[header]
name = "CBaseEntity_TakeDamageOld"
addr = 0xd51100
type = "long long"

[header.args]
