last_change = 2026-08-15T07:57:57.042998Z
addr = 0xf2d750
size = 0x268
name = "CSpawnGroupMgrGameSystem_SetActiveSpawnGroup"
type = "long long"

[header]
name = "CSpawnGroupMgrGameSystem_SetActiveSpawnGroup"
addr = 0xf2d750
type = "long long"

[header.args]
