last_change = 2026-08-15T07:57:57.042988Z
addr = 0xf2c090
size = 0x168
name = "CBaseEntity_EmitSoundFilter"
type = "long long"

[header]
name = "CBaseEntity_EmitSoundFilter"
addr = 0xf2c090
type = "long long"

[header.args]
