last_change = 2026-08-15T07:57:57.042991Z
addr = 0xf2cd10
size = 0x492
name = "CSpawnGroupMgrGameSystem_SpawnGroupInit"
type = "long long"

[header]
name = "CSpawnGroupMgrGameSystem_SpawnGroupInit"
addr = 0xf2cd10
type = "long long"

[header.args]
