last_change = 2026-08-15T07:57:57.042996Z
addr = 0xf2d2f0
size = 0x45c
name = "CSpawnGroupMgrGameSystem_CreateLoadingSpawnGroup"
type = "long long"

[header]
name = "CSpawnGroupMgrGameSystem_CreateLoadingSpawnGroup"
addr = 0xf2d2f0
type = "long long"

[header.args]
