last_change = 2026-08-16T09:32:18.913774Z
addr = 0xf393c0
size = 0x3f3
name = "CSpawnGroupMgrGameSystem_DumpSpawnGroups"
type = "void"

[header]
name = "CSpawnGroupMgrGameSystem_DumpSpawnGroups"
addr = 0xf393c0
type = "void"

[header.args]
