last_change = 2026-08-15T07:57:57.043000Z
addr = 0xf307c0
size = 0x64c
name = "CSpawnGroupMgrGameSystem_SpawnGroupActuallyShutdown"
type = "double"

[header]
name = "CSpawnGroupMgrGameSystem_SpawnGroupActuallyShutdown"
addr = 0xf307c0
type = "double"

[header.args]
