last_change = 2026-08-16T09:32:18.913791Z
addr = 0xf5ce20
size = 0x311
name = "CSpawnGroupMgrGameSystem_UnloadSpawnGroup"
type = "double"

[header]
name = "CSpawnGroupMgrGameSystem_UnloadSpawnGroup"
addr = 0xf5ce20
type = "double"

[header.args]
