last_change = 2026-08-15T07:57:57.043108Z
addr = 0xf9e020
size = 0x9704
name = "CBaseEntity_GetScriptDescInternal"
type = "unsigned long long *"

[header]
name = "CBaseEntity_GetScriptDescInternal"
addr = 0xf9e020
type = "unsigned long long *"

[header.args]
