last_change = 2026-08-16T09:32:35.418384Z
addr = 0x1388d50
size = 0x607
name = "CCSGameRules_BeginRound"
type = "long long"

[header]
name = "CCSGameRules_BeginRound"
addr = 0x1388d50
type = "long long"

[header.args]
