last_change = 2026-08-16T09:32:18.914205Z
addr = 0x14d8970
size = 0x45
name = "CCSPlayerController_HandleCommandDrop"
type = "char *"

[header]
name = "CCSPlayerController_HandleCommandDrop"
addr = 0x14d8970
type = "char *"

[header.args]
