last_change = 2026-08-15T07:57:57.043172Z
addr = 0x14ebcf0
size = 0x2a3
name = "CCSPlayerController_Respawn"
type = "long long"

[header]
name = "CCSPlayerController_Respawn"
addr = 0x14ebcf0
type = "long long"

[header.args]
