last_change = 2026-08-16T09:32:36.369891Z
addr = 0x15329e0
size = 0xa50
name = "GiveNamedItem"
type = "unsigned long long *"

[header]
name = "GiveNamedItem"
addr = 0x15329e0
type = "unsigned long long *"

[header.args]
