last_change = 2026-08-15T07:57:57.043224Z
addr = 0x1549820
size = 0xc87
name = "CCSPlayer_ItemServices_CanAcquire"
type = "long long"

[header]
name = "CCSPlayer_ItemServices_CanAcquire"
addr = 0x1549820
type = "long long"

[header.args]
