last_change = 2026-08-15T07:57:57.043251Z
addr = 0x158e710
size = 0x206
name = "CCSPlayer_WeaponServices_SelectItem"
type = "long long"

[header]
name = "CCSPlayer_WeaponServices_SelectItem"
addr = 0x158e710
type = "long long"

[header.args]
