last_change = 2026-08-16T09:32:18.914367Z
addr = 0x1581220
size = 0x662
name = "CCSPlayer_MovementServices_CheckVelocity"
type = "unsigned long long"

[header]
name = "CCSPlayer_MovementServices_CheckVelocity"
addr = 0x1581220
type = "unsigned long long"

[header.args]
