last_change = 2026-08-15T07:57:57.043266Z
addr = 0x15cfd10
size = 0x215
name = "CCSPlayerPawn_OnTakeDamage"
type = "long long (__fastcall *)()"

[header]
name = "CCSPlayerPawn_OnTakeDamage"
addr = 0x15cfd10
type = "long long (__fastcall *)()"

[header.args]
