last_change = 2026-08-16T09:32:18.914430Z
addr = 0x15cfd10
size = 0x215
name = "CCSPlayerPawn_OnTakeDamage"
type = "void (*)()"

[header]
name = "CCSPlayerPawn_OnTakeDamage"
addr = 0x15cfd10
type = "void (*)()"

[header.args]
