last_change = 2026-08-15T07:57:57.043311Z
addr = 0x16281f0
size = 0x583
name = "CBasePlayerController_ProcessUsercmds"
type = "long long"

[header]
name = "CBasePlayerController_ProcessUsercmds"
addr = 0x16281f0
type = "long long"

[header.args]
