last_change = 2026-08-15T07:57:57.043337Z
addr = 0x169e410
size = 0x270
name = "CGameEntitySystem_FindEntityProcedural"
type = "long long"

[header]
name = "CGameEntitySystem_FindEntityProcedural"
addr = 0x169e410
type = "long long"

[header.args]
