last_change = 2026-08-15T07:57:57.043344Z
addr = 0x16a7a80
size = 0x1fe
name = "CEntitySaveRestoreBlockHandler_PreSave"
type = "long long"

[header]
name = "CEntitySaveRestoreBlockHandler_PreSave"
addr = 0x16a7a80
type = "long long"

[header.args]
