last_change = 2026-08-16T09:32:38.720979Z
addr = 0x16a7e40
size = 0x2dc
name = "CEntitySaveRestoreBlockHandler_RestoreEntity"
type = "long long"

[header]
name = "CEntitySaveRestoreBlockHandler_RestoreEntity"
addr = 0x16a7e40
type = "long long"

[header.args]
