last_change = 2026-08-15T07:57:57.043340Z
addr = 0x16a74d0
size = 0x375
name = "CEntitySaveRestoreBlockHandler_SaveInternal"
type = "long long"

[header]
name = "CEntitySaveRestoreBlockHandler_SaveInternal"
addr = 0x16a74d0
type = "long long"

[header.args]
