last_change = 2026-08-15T07:57:57.043395Z
addr = 0x16e5b00
size = 0xbc0
name = "CEntitySaveRestoreBlockHandler_Restore"
type = "long long"

[header]
name = "CEntitySaveRestoreBlockHandler_Restore"
addr = 0x16e5b00
type = "long long"

[header.args]
