last_change = 2026-08-15T07:57:57.043439Z
addr = 0x1718180
size = 0x6d
name = "CLoopModeGame_SetWorldSession"
type = "void"

[header]
name = "CLoopModeGame_SetWorldSession"
addr = 0x1718180
type = "void"

[header.args]
