last_change = 2026-08-15T07:57:57.043463Z
addr = 0x172b790
size = 0x13
name = "CLoopModeGame_LoopInit"
type = "long long"

[header]
name = "CLoopModeGame_LoopInit"
addr = 0x172b790
type = "long long"

[header.args]
