last_change = 2026-08-15T07:57:57.043451Z
addr = 0x17214f0
size = 0x6f
name = "CLoopModeFactory_CLoopModeGame_Shutdown"

[header]
name = "CLoopModeFactory_CLoopModeGame_Shutdown"
addr = 0x17214f0

[header.args]
