last_change = 2026-08-16T09:32:18.915294Z
addr = 0x17f1780
size = 0x325
name = "EntInfo_CommandHandler"
type = "void"

[header]
name = "EntInfo_CommandHandler"
addr = 0x17f1780
type = "void"

[header.args]
