last_change = 2026-08-15T07:57:57.043577Z
addr = 0x17f3ac0
size = 0x693
name = "GiveCommand"
type = "unsigned long long *"

[header]
name = "GiveCommand"
addr = 0x17f3ac0
type = "unsigned long long *"

[header.args]
