last_change = 2026-08-15T07:57:57.043597Z
addr = 0x1825dd0
size = 0x129
name = "CBaseEntity_OnSetDormant"
type = "long long"

[header]
name = "CBaseEntity_OnSetDormant"
addr = 0x1825dd0
type = "long long"

[header.args]
