last_change = 2026-08-15T07:57:57.043673Z
addr = 0x18ded50
size = 0x392
name = "CSource2GameClients_OnClientConnected"
type = "unsigned long long"

[header]
name = "CSource2GameClients_OnClientConnected"
addr = 0x18ded50
type = "unsigned long long"

[header.args]
