last_change = 2026-08-15T07:58:21.063603Z
addr = 0x18eb620
size = 0x8d0
name = "CSource2GameClients_ClientDiagnostic"
type = "long long"

[header]
name = "CSource2GameClients_ClientDiagnostic"
addr = 0x18eb620
type = "long long"

[header.args]
