last_change = 2026-08-16T09:32:18.915614Z
addr = 0x18e90a0
size = 0x11f
name = "CSource2GameClients_ClientCommand"
type = "void"

[header]
name = "CSource2GameClients_ClientCommand"
addr = 0x18e90a0
type = "void"

[header.args]
