last_change = 2026-08-16T09:32:44.686905Z
addr = 0x18f8c60
size = 0x217
name = "CGameRules_ClientSettingsChanged"
type = "long long"

[header]
name = "CGameRules_ClientSettingsChanged"
addr = 0x18f8c60
type = "long long"

[header.args]
