last_change = 2026-08-15T07:57:57.043701Z
addr = 0x192fcb0
size = 0x6e
name = "CMultiplayRules_ClientDisconnected"
type = "long long"

[header]
name = "CMultiplayRules_ClientDisconnected"
addr = 0x192fcb0
type = "long long"

[header.args]
