last_change = 2026-08-15T07:57:57.043709Z
addr = 0x195bb40
size = 0x2c
name = "CBaseEntity_VPhysicsEndTouch"
type = "long long"

[header]
name = "CBaseEntity_VPhysicsEndTouch"
addr = 0x195bb40
type = "long long"

[header.args]
