last_change = 2026-08-15T07:57:57.043728Z
addr = 0x199fd00
size = 0x1a6
name = "CPlayerCommandQueue_ctor"
type = "long long"

[header]
name = "CPlayerCommandQueue_ctor"
addr = 0x199fd00
type = "long long"

[header.args]
