last_change = 2026-08-15T07:57:57.043782Z
addr = 0x210c060
size = 0x68
name = "CEntityInstance_AcceptInput"
type = "long long"

[header]
name = "CEntityInstance_AcceptInput"
addr = 0x210c060
type = "long long"

[header.args]
