last_change = 2026-08-15T07:57:57.043772Z
addr = 0x2109f80
size = 0x22
name = "CEntityInstance_PostDataUpdateDelta"
type = "long long (*)(void)"

[header]
name = "CEntityInstance_PostDataUpdateDelta"
addr = 0x2109f80
type = "long long (*)(void)"

[header.args]
