last_change = 2026-08-15T07:57:57.043763Z
addr = 0x21089d0
size = 0x515
name = "CEntityIdentity_AcceptInputInternal"
type = "long long"

[header]
name = "CEntityIdentity_AcceptInputInternal"
addr = 0x21089d0
type = "long long"

[header.args]
