last_change = 2026-08-16T09:32:18.915859Z
addr = 0x21084e0
size = 0x39e
name = "CEntityIdentity_SetEntityName"
type = "double"

[header]
name = "CEntityIdentity_SetEntityName"
addr = 0x21084e0
type = "double"

[header.args]
