last_change = 2026-08-15T07:57:57.043788Z
addr = 0x2111940
size = 0x1b4
name = "CEntityKeyValues_LoadFromContext"
type = "long long"

[header]
name = "CEntityKeyValues_LoadFromContext"
addr = 0x2111940
type = "long long"

[header.args]
