last_change = 2026-08-15T07:57:57.043796Z
addr = 0x2112f40
size = 0x18a
name = "CEntitySystem_Activate"
type = "long long"

[header]
name = "CEntitySystem_Activate"
addr = 0x2112f40
type = "long long"

[header.args]
