last_change = 2026-08-15T07:57:57.043852Z
addr = 0x2128270
size = 0x1c3
name = "CEntitySystem_ExecuteQueuedCreation"
type = "long long"

[header]
name = "CEntitySystem_ExecuteQueuedCreation"
addr = 0x2128270
type = "long long"

[header.args]
