last_change = 2026-08-15T07:57:57.043840Z
addr = 0x2124530
size = 0x16a
name = "CEntitySystem_QueueSpawnEntity"
type = "long long"

[header]
name = "CEntitySystem_QueueSpawnEntity"
addr = 0x2124530
type = "long long"

[header.args]
