last_change = 2026-08-16T09:32:18.916075Z
addr = 0x2124530
size = 0x16a
name = "CEntitySystem_QueueSpawnEntity"
type = "void"

[header]
name = "CEntitySystem_QueueSpawnEntity"
addr = 0x2124530
type = "void"

[header.args]
