last_change = 2026-08-15T07:57:57.043860Z
addr = 0x2129f80
size = 0x24a
name = "CEntitySystem_RegisterEntityClass"
type = "long long"

[header]
name = "CEntitySystem_RegisterEntityClass"
addr = 0x2129f80
type = "long long"

[header.args]
