last_change = 2026-08-15T07:57:57.043874Z
addr = 0x2135b80
size = 0x7f3
name = "CEntitySystem_Init"
type = "long long"

[header]
name = "CEntitySystem_Init"
addr = 0x2135b80
type = "long long"

[header.args]
